name: Trickest CVE Monitor And Deploy
on:
  schedule:
    - cron: "0 * * * *" # 每小时检查一次
  workflow_dispatch:

jobs:
  sync_with_upstream:
    name: Sync with Upstream
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: trickest/cve
          upstream_sync_branch: main
          target_sync_branch: main
          test_mode: false

      - name: Check for Failure
        if: failure()
        run: |
          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
          exit 1

  deploy_cve_poc_md:
    name: Sync with Upstream
    runs-on: ubuntu-latest
    needs: sync_with_upstream

    steps:
      - name: Generate Docsify Site
        run: |
          mkdir docs
          rsync -av --include='[0-9][0-9][0-9][0-9]/' --include='[0-9][0-9][0-9][0-9]/*.md' --exclude='*' --exclude="docs/" --exclude="summary_html/"  . docs/
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/docs/README.html" /></head></html>' > index.html

      - name: Generate Docsify Sidebar
        uses: if-nil/docsify-file-catalog-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          include: "docs/.*"

      - name: Move Sidebar to doc dir
        run: |
          mv _sidebar.md docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./trickest-cve/docs
