name: Trickest CVE Monitor And Deploy
on:
  schedule:
    - cron: "0 * * * *" # 每小时检查一次
  workflow_dispatch:

jobs:
  monitor-fork:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Check for updates in upstream repository
        run: |
          git clone https://github.com/trickest/cve trickest-cve
          cd trickest-cve
          git fetch
          UPDATES=$(git log HEAD..origin/main --oneline)
          if [ -n "$UPDATES" ]; then
            echo "New updates detected. Forking repository."
            git merge upstream/main --allow-unrelated-histories --no-edit
          else
            echo "No updates detected."
            exit 0
          fi

      - name: Generate Docsify Site
        run: |
          cd trickest-cve
          mkdir docs
          rsync -av --include='[0-9][0-9][0-9][0-9]/' --include='[0-9][0-9][0-9][0-9]/*.md' --exclude='*' --exclude="docs/" --exclude="summary_html/"  . docs/
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/docs/README.html" /></head></html>' > index.html

      - name: Generate Docsify Sidebar
        uses: if-nil/docsify-file-catalog-action@main # 使用action生成_sidebar.md文件并推送到仓库内
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN 需要有写权限
          include: 'docs/.*'

      - name: Move Sidebar to doc dir
        run: |
          mv _sidebar.md docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./trickest-cve/docs
